version: '3'
services:
    sense-postgres:
        image: sense/postgresql:9
        ports:
                - 5432:5432
        volumes:
            - sense-postgres-data:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_PASSWORD: "mypassword"
            PGDATA: "/var/lib/postgresql/data/pgdata"

    frontend-httpd:
        image: sense-proxy/httpd:2.4
        ports:
          - 80:80


volumes:
    sense-postgres-data:
